/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.training.service.builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the userext service. Represents a row in the &quot;userext&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.training.service.builder.model.impl.userextModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.training.service.builder.model.impl.userextImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see userext
 * @generated
 */
@ProviderType
public interface userextModel
	extends BaseModel<userext>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a userext model instance should use the {@link userext} interface instead.
	 */

	/**
	 * Returns the primary key of this userext.
	 *
	 * @return the primary key of this userext
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this userext.
	 *
	 * @param primaryKey the primary key of this userext
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this userext.
	 *
	 * @return the uuid of this userext
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this userext.
	 *
	 * @param uuid the uuid of this userext
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the userext ID of this userext.
	 *
	 * @return the userext ID of this userext
	 */
	public long getUserextId();

	/**
	 * Sets the userext ID of this userext.
	 *
	 * @param userextId the userext ID of this userext
	 */
	public void setUserextId(long userextId);

	/**
	 * Returns the group ID of this userext.
	 *
	 * @return the group ID of this userext
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this userext.
	 *
	 * @param groupId the group ID of this userext
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this userext.
	 *
	 * @return the company ID of this userext
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this userext.
	 *
	 * @param companyId the company ID of this userext
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this userext.
	 *
	 * @return the user ID of this userext
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this userext.
	 *
	 * @param userId the user ID of this userext
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this userext.
	 *
	 * @return the user uuid of this userext
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this userext.
	 *
	 * @param userUuid the user uuid of this userext
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this userext.
	 *
	 * @return the user name of this userext
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this userext.
	 *
	 * @param userName the user name of this userext
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this userext.
	 *
	 * @return the create date of this userext
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this userext.
	 *
	 * @param createDate the create date of this userext
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this userext.
	 *
	 * @return the modified date of this userext
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this userext.
	 *
	 * @param modifiedDate the modified date of this userext
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the screen name of this userext.
	 *
	 * @return the screen name of this userext
	 */
	@AutoEscape
	public String getScreenName();

	/**
	 * Sets the screen name of this userext.
	 *
	 * @param screenName the screen name of this userext
	 */
	public void setScreenName(String screenName);

	/**
	 * Returns the email of this userext.
	 *
	 * @return the email of this userext
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this userext.
	 *
	 * @param email the email of this userext
	 */
	public void setEmail(String email);

	/**
	 * Returns the office ID of this userext.
	 *
	 * @return the office ID of this userext
	 */
	public long getOfficeID();

	/**
	 * Sets the office ID of this userext.
	 *
	 * @param officeID the office ID of this userext
	 */
	public void setOfficeID(long officeID);

	/**
	 * Returns the office location of this userext.
	 *
	 * @return the office location of this userext
	 */
	@AutoEscape
	public String getOfficeLocation();

	/**
	 * Sets the office location of this userext.
	 *
	 * @param officeLocation the office location of this userext
	 */
	public void setOfficeLocation(String officeLocation);

	/**
	 * Returns the office designation of this userext.
	 *
	 * @return the office designation of this userext
	 */
	@AutoEscape
	public String getOfficeDesignation();

	/**
	 * Sets the office designation of this userext.
	 *
	 * @param officeDesignation the office designation of this userext
	 */
	public void setOfficeDesignation(String officeDesignation);

	/**
	 * Returns the reporting to of this userext.
	 *
	 * @return the reporting to of this userext
	 */
	@AutoEscape
	public String getReportingTo();

	/**
	 * Sets the reporting to of this userext.
	 *
	 * @param reportingTo the reporting to of this userext
	 */
	public void setReportingTo(String reportingTo);

}